Update dialyzer
The previous version failed in CI with some weird error:

```
Checking PLT...
** (Protocol.UndefinedError) protocol String.Chars not implemented for {~c"no such file or directory", ~c"decimal.app"} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version, Version.Requirement
    (elixir 1.17.3) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.17.3) lib/string/chars.ex:22: String.Chars.to_string/1
    (dialyxir 0.5.1) lib/dialyxir/project.ex:189: Dialyxir.Project.deps_app/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (dialyxir 0.5.1) lib/dialyxir/project.ex:195: Dialyxir.Project.deps_app/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
Error: Process completed with exit code 1.
```

To fix this I simply updated dialyzer because the last version we used
(0.5.1) was from 2017.

This required two configuration changes: `race_conditions` option is no
longer supported so I removed that, and same goes for the halt exit
status option.

The new version also found one function clause that is guaranteed to
fail when called - it passed a string to a :amqp_connection.start
function even though that function expects a list of options. Likely
this has not been a problem since none of our applications use freddy in
way where thay specify a connection string and all just use
configuration option list instead.

AUTO-1830